### ISSUE TITLE
Create seed data for integration testing

### ISSUE THREAD

**Issue by fluxynet** [lsldigital/somesql#2]
SQL file to be created in a folder `test/` as `data.sql`

Base table data structure as follows:

id: uuid
data: jsonb
created_at: datetime with timezone
updated_at: datetime with timezone
owner_id: uuid (resource owner)
type: content type (typically author / article / category)
slug: string

Seed data for the following scenario:

```
author --< article >---< category
```

Author does not store article information
Article has `author_id`
Article has `category_ids`
Category does not store article information

**Comment by nadimattari** [comment]
Sample seed data added, together with create statement.
